language: node_js
node_js:
  - "6.14"
  - "7.10"
  - "8.11.3"
  - "9.11.2"
sudo: false
cache:
  directories:
    - node_modules
before_install:
  # Update Node modules
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"
script:
  - "npm run lint"
  - "npm test"
after_success:
  - "npm run coveralls"